using System;
using System.Collections.Generic;

#nullable disable

namespace Reprint_Patient_Card_BioLab.Models
{
    public partial class LabInfo
    {
        public string LabName { get; set; }
        public string LabTelephone { get; set; }
        public string LabFax { get; set; }
        public string LabEmail { get; set; }
        public string LabUrl { get; set; }
        public string LabAddress { get; set; }
        public string Munit { get; set; }
        public string InvType { get; set; }
        public string InvPeriod { get; set; }
        public string InvStart { get; set; }
        public string InvserDate { get; set; }
        public bool InvnLock { get; set; }
        public string InvResDate { get; set; }
        public string UpdateDb { get; set; }
        public bool? TestmPrice { get; set; }
        public bool? TestsReset { get; set; }
        public bool? TestKits { get; set; }
        public string BranchPrefix { get; set; }
        public int? Labpclass { get; set; }
        public string Msg { get; set; }
        public string Title { get; set; }
        public string Sign { get; set; }
        public string Spec { get; set; }
        public string Labpass { get; set; }
        public bool? Fieldsname { get; set; }
        public string Currency { get; set; }
        public bool? ShowLabName { get; set; }
        public bool? Allowemptypatnamear { get; set; }
        public string Labsubtitel { get; set; }
        public bool? Showcheckedby { get; set; }
        public double? Topmargin { get; set; }
        public double? Buttommargin { get; set; }
        public string Qc { get; set; }
        public int? Logofftime { get; set; }
        public bool? Enablelogoff { get; set; }
        public bool? Separetedsheet { get; set; }
        public bool? Reportcolor { get; set; }
        public int? Workdays { get; set; }
        public bool? AllowEmptyPatNameEn { get; set; }
        public bool? AllowEmptyrefNameEn { get; set; }
        public int? Seminrpt { get; set; }
        public int? AllowHideRefOne { get; set; }
        public int? AllowHideRefTow { get; set; }
        public int? FontSize { get; set; }
        public int? ShowLine { get; set; }
        public int? TypeLine { get; set; }
        public int? TranPen { get; set; }
        public int? Barcode { get; set; }
        public decimal? Setbarcode { get; set; }
        public int? Stoolrpt { get; set; }
        public int? Cbcrpt { get; set; }
        public int? Svoucher { get; set; }
        public int? Pvoucher { get; set; }
        public string ALabname { get; set; }
        public string ELabname { get; set; }
        public string ADetails1 { get; set; }
        public string ADetails2 { get; set; }
        public string ADetails3 { get; set; }
        public string EDetails1 { get; set; }
        public string EDetails2 { get; set; }
        public string EDetails3 { get; set; }
        public string AAddress { get; set; }
        public string EAddress { get; set; }
        public string Being { get; set; }
        public int? Urinerpt { get; set; }
        public string BackupPath { get; set; }
        public int? CrresRpt { get; set; }
        public int? Microbiologyrpt { get; set; }
        public int? MsgType { get; set; }
        public string WsheetFontSize { get; set; }
        public int? HideLogo { get; set; }
        public int? HInvoice { get; set; }
        public int? DInvoice { get; set; }
        public int? HWorksheetSize { get; set; }
        public int? ConnectAcc { get; set; }
        public bool? Connectionacc { get; set; }
        public int? Rpttype { get; set; }
        public int? ConnectInv { get; set; }
        public string HedeerEmail { get; set; }
        public string FooterEmail { get; set; }
        public string FooterResultWeb { get; set; }
        public int? TMax { get; set; }
        public DateTime? Dend { get; set; }
        public string IpserverConnection { get; set; }
        public string FooterResult { get; set; }
        public string OutputPsm { get; set; }
        public string IncomePsm { get; set; }
        public bool? Connectionpsm { get; set; }
        public string InvoiceComment { get; set; }
        public string PathSendEmail { get; set; }
        public string PathSendFax { get; set; }
        public int? ArResultready { get; set; }
        public int? EnResultready { get; set; }
        public string ArMsgresultready { get; set; }
        public int? EnMsgresultready { get; set; }
        public int? SendSmswhenReady { get; set; }
        public int? Revision { get; set; }
        public int? ReplaceNr { get; set; }
        public string ReplaceNrword { get; set; }
        public int? WorkSheetForm { get; set; }
        public string InvoiceArchive { get; set; }
        public decimal? DotnetVersion { get; set; }
        public bool? Connectionhr { get; set; }
        public string UserNameSendpassword { get; set; }
        public string PasswordSendpassword { get; set; }
        public int? Enachk { get; set; }
        public string EmailNotification { get; set; }
        public int? CloseCash { get; set; }
        public int? SendFaxOutlook { get; set; }
        public string NotificationSms { get; set; }
        public string NotificationSmspre { get; set; }
        public string NotificationSmssuf { get; set; }
        public string PathLogo { get; set; }
        public string NotReceivedInsurance { get; set; }
        public string NotReceivedOutPatient { get; set; }
        public string ReferralCreditNotification { get; set; }
        public int? ConnectWithinfinity { get; set; }
        public int? ConnectWithArchive { get; set; }
        public bool? UseLangOption { get; set; }
        public int? DefaultLangId { get; set; }
        public string PathOfVersionUpdate { get; set; }
        public string Pdfpsmresult { get; set; }
        public int? AllowViewPdfresult { get; set; }
        public bool? ConnectWithHr { get; set; }
        public bool? ConnectWithAcc { get; set; }
        public int? LogOutTime { get; set; }
        public int? Smsprovider { get; set; }
        public int? MedicalInformationRequirement { get; set; }
        public int? CurrancyId { get; set; }
        public int? FlutterVersion { get; set; }
    }
}
